
EXE 	:= test
OBJ_DIR := ./obj
RM 	:= rm -rf
LD 	:= g++
CC 	:= g++
CCFLAG	:= -g -Wall
#CCFLAG	+= -D_DEBUG -DDETAILS -DSTABLE_CHECK

$(EXE): $(OBJ_DIR)/nth_element.o
	$(LD) -o $@ $^

$(OBJ_DIR)/%.o : %.cpp *.h
	$(CC) $(CCFLAG) -o $@ -c $<

clean:
	$(RM) $(EXE) $(OBJ_DIR)/*.o
